Date and time
CS3733-D20-Team-N/CS3733-D20-Team-N-Iterations pull request #122
Opened 2020-04-27 21:29 UTC by ieroshenko

2020-04-27 21:34 UTC, Noah-C-S requested changes

2020-04-27 21:34 UTC, Noah-C-S commented on src/main/java/edu/wpi/N/Main.java
> +    // MapDB.initDB();
Uhhhh why do you comment out initDB in main?

2020-04-27 21:41 UTC, seungho715 submitted a review, later dismissed

2020-04-28 02:45 UTC, njwood approved these changes

2020-04-28 02:47 UTC, ieroshenko reviewed
okay...

2020-04-28 02:47 UTC, emllewellyn approved these changes

2020-04-28 03:13 UTC, Noah-C-S approved these changes

2020-04-28 08:10 UTC, merged