Floral service done
CS3733-D20-Team-N/CS3733-D20-Team-N-Iterations pull request #123
Opened 2020-04-27 21:39 UTC by npelletier2

2020-04-27 21:45 UTC, seungho715 submitted a review, later dismissed

2020-04-27 21:47 UTC, ieroshenko submitted a review, later dismissed

2020-04-27 21:52 UTC, ieroshenko submitted a review, later dismissed

2020-04-27 21:52 UTC, seungho715 submitted a review, later dismissed

2020-04-27 22:03 UTC, seungho715 submitted a review, later dismissed

2020-04-27 22:47 UTC, Noah-C-S requested changes
see comments

2020-04-27 22:47 UTC, Noah-C-S commented on src/main/java/edu/wpi/N/views/sanitationController.java
> +    int transReq = ServiceDB.addTransReq(notes, nodeID, langSelection);
Sanitation controller seems to add translator requests.... That doesn't seem quite right. It should add sanitation requests.

2020-04-27 22:47 UTC, Noah-C-S commented on src/main/java/edu/wpi/N/entities/request/FlowerRequest.java
> +    return flowerList;
As I said before, you should **absolutely not** create **any** new methods in any subclasses of request. You should only overrride request's methods. This is what getAtr1, getAtr2, etc. etc. are for. For example, getPatientName should be replaced with an override of getAtr1.

2020-04-27 22:47 UTC, Noah-C-S commented on src/main/java/edu/wpi/N/entities/request/FlowerRequest.java
> +    this.flowerList = flowerList;
Entities returned from the database should be immutable, so this shouldn't be a function.

2020-04-27 22:47 UTC, Noah-C-S commented on src/main/java/edu/wpi/N/entities/request/FlowerRequest.java
> +    HashMap<String, Integer> acc = new HashMap<>();
I suppose this works, but why do this? It's much easier (computationally and diagrammatically speaking) to use SQL to get the flowers using group by. I talk more about this when you call the constructor.

2020-04-27 22:47 UTC, Noah-C-S commented on src/main/java/edu/wpi/N/database/ServiceDB.java
> +            "SELECT flower.* FROM flower, flowertoflower WHERE flower.flowerName = flowertoflower.flowerName AND flowertoflower.requestID = ?";
`SELECT flower.flowerName, count(flower.flowerName) AS flowerCount FROM flower, flowertoflower WHERE flower.flowerName = flowertoflower.flowerName AND flowertoflower.requestID = ? GROUP BY flower.flowerName` is more what you're looking for. In the returned resultSet, flowerName will be the name of the flower and flowerCount will be amount of that particular flower was ordered. Then, you can simply construct the string with `String flowers = ""` followed by `flowers = flowers + ", " + rx.getInt("flowerCount") + " " + "rx.getString("flowerName")` in the resultSet loop. Much much much easier and much much much better to do it this way; definitely worth refactoring now.

2020-04-27 22:47 UTC, Noah-C-S commented on src/main/java/edu/wpi/N/database/ServiceDB.java
> +            "SELECT flower.* FROM flower, flowertoflower WHERE flower.flowerName = flowertoflower.flowerName AND flowertoflower.requestID = ?";
Same as below in getRequests.

2020-04-27 22:47 UTC, Noah-C-S commented on src/main/resources/edu/wpi/N/sql/setup.sql
> +    price FLOAT NOT NULL
There is no reason to make the price a float. At first glance, the statement "use a float whenever you need any numbers which aren't integers" seems correct and valid, but if you look at what floating point numbers are and what they're for, it can be shown that this isn't the case; they should only be used when you need to store numbers which have an arbitrary decimal place. A floating point number is simply a number which allows the decimal to be in any point of the number. However, an integer isn't "a number without a decimal place", it is "a number with a KNOWN decimal place". You always know the decimal place in a price will be two digits right of the final digit, so why store it as a floating point number when you could store it as an int (a fixed point number).
Or, to put it another way, just store the price in cents rather than dollars and use an integer data type.

2020-04-27 22:47 UTC, Noah-C-S commented on src/main/resources/edu/wpi/N/sql/setup.sql
> +    price FLOAT NOT NULL
of course it's like a tiny bit more work to convert it later, but `"$" + price/100 + String.format(".%02d", price % 100)` should convert it to a string perfectly.

2020-04-28 00:20 UTC, npelletier2 commented on src/main/java/edu/wpi/N/views/sanitationController.java
> +    int transReq = ServiceDB.addTransReq(notes, nodeID, langSelection);
The sanitation controller that I did is on another branch. This was just edited to comment out a line that was causing Travis CI to fail.

2020-04-28 01:23 UTC, Noah-C-S approved these changes
looks good. yay

2020-04-28 02:12 UTC, seungho715 approved these changes

2020-04-28 02:12 UTC, merged