Random u ifixes
CS3733-D20-Team-N/CS3733-D20-Team-N-Iterations pull request #343
Opened 2020-05-09 22:53 UTC by kofichtner

- edits wheelchair service request text overflow on location box
- moves map editor panel to upper right
- swaps floor change buttons with current floor button
- uses map editor side bar
- adds quick access buttons for exits and INFO
- changes background color depending on map

2020-05-09 23:21 UTC, Noah-C-S requested changes
Looks all right, though I think it would be a lot nicer if the buttons had a cursor of hand rather than inherit and if they had a hover style which changed their border or something. The info button should be fixed such that it's clear that it doesn't work in Faulkner before you click it, though, and you should check the selected node rather than the current building since as is, if I select a node in faulkner, switch to main building, and click the button it tells me to select a starting node.

2020-05-09 23:21 UTC, Noah-C-S commented on src/main/java/edu/wpi/N/views/mapDisplay/NewMapDisplayController.java
> +              if (currentBuilding.equals("Faulkner")) {
Should probably base this on the building of the selected node rather than the building of the map, and the button should appear disabled if the current building is Fualkner.

2020-05-10 00:30 UTC, kofichtner commented on src/main/java/edu/wpi/N/views/mapDisplay/NewMapDisplayController.java
> +              if (currentBuilding.equals("Faulkner")) {
okay i made the changes except the CSS stuff to make buttons look more clickable, i will get to that later when we are doing more CSS on map display page

2020-05-10 00:50 UTC, kofichtner commented on src/main/java/edu/wpi/N/views/mapDisplay/NewMapDisplayController.java
> +              if (currentBuilding.equals("Faulkner")) {
added the cursor hand thing too

2020-05-10 01:58 UTC, ieroshenko approved these changes

2020-05-10 01:59 UTC, njwood approved these changes

2020-05-10 02:03 UTC, Noah-C-S approved these changes

2020-05-10 02:23 UTC, merged